# 5단계: 클러스터 범위의 GatewayClass. 이 class를 담당할 Envoy 컨트롤러를 지정한다.
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: gateway-lab-envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
