apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_PROFILES_ACTIVE: local
  APP_ENVIRONMENT: local
  DEPLOYMENT_PLATFORM: kubernetes
  JAVA_TOOL_OPTIONS: >-
    -XX:InitialRAMPercentage=25.0
    -XX:MaxRAMPercentage=75.0
    -Duser.timezone=UTC
  BACKEND_URL: http://backend:8081
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  JWT_ISSUER: local-gateway
  JWT_AUDIENCE: gateway-sample-api
  JWT_TTL: 1h
  RATE_LIMIT_REPLENISH_RATE: "2"
  RATE_LIMIT_BURST_CAPACITY: "5"
  CORS_ALLOWED_ORIGINS: http://localhost:3000
  BACKEND_CONNECT_TIMEOUT_MS: "2000"
  BACKEND_RESPONSE_TIMEOUT: 5s
  BACKEND_MAX_CONNECTIONS: "50"
  SERVER_NETTY_CONNECTION_TIMEOUT: 2s
  SERVER_NETTY_IDLE_TIMEOUT: 30s
  SERVER_NETTY_MAX_KEEP_ALIVE_REQUESTS: "1000"
  SERVER_TOMCAT_CONNECTION_TIMEOUT: 5s
  SERVER_TOMCAT_KEEP_ALIVE_TIMEOUT: 30s
  SERVER_TOMCAT_MAX_CONNECTIONS: "500"
  SERVER_TOMCAT_ACCEPT_COUNT: "100"
  SERVER_TOMCAT_THREADS_MAX: "50"
  SERVER_TOMCAT_THREADS_MIN_SPARE: "5"
  TRACING_SAMPLING_PROBABILITY: "1.0"
  OTEL_EXPORT_ENABLED: "false"
  PROMETHEUS_PUBLIC: "false"
